/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI; 
import Controladores.*;
import Logica.*;
import javax.swing.*;

/**
 *
 * @author Jhoan Sebasti�n
 */

public class GUI_Login extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI_Login
     */
    ControladorAdministrador controladorAdministrador;
    ControladorGerente controladorGerente;
    ControladorOperador controladorOperador;
    
    public GUI_Login(){
        
        initComponents();
        controladorAdministrador = new ControladorAdministrador();
        controladorGerente = new ControladorGerente();
        controladorOperador = new ControladorOperador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        TxtPass = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JButton();
        botonOlvide = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        TxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsuario.setFont(new java.awt.Font("Cambria", 2, 36)); // NOI18N
        TxtUsuario.setText("Usuario:");
        jPanel1.add(TxtUsuario);
        TxtUsuario.setBounds(890, 200, 180, 70);

        usuario.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        jPanel1.add(usuario);
        usuario.setBounds(890, 270, 250, 50);

        TxtPass.setBackground(new java.awt.Color(255, 255, 255));
        TxtPass.setFont(new java.awt.Font("Cambria", 2, 36)); // NOI18N
        TxtPass.setText("Contraseña:");
        jPanel1.add(TxtPass);
        TxtPass.setBounds(890, 340, 200, 70);

        pass.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        jPanel1.add(pass);
        pass.setBounds(890, 410, 250, 50);

        botonIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IngresarMed.png"))); // NOI18N
        botonIniciarSesion.setBorder(null);
        botonIniciarSesion.setBorderPainted(false);
        botonIniciarSesion.setContentAreaFilled(false);
        botonIniciarSesion.setFocusPainted(false);
        botonIniciarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IngresarPeq.png"))); // NOI18N
        botonIniciarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ingresar.png"))); // NOI18N
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(botonIniciarSesion);
        botonIniciarSesion.setBounds(890, 470, 240, 120);

        botonOlvide.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        botonOlvide.setText("Olvidé mi contraseña");
        jPanel1.add(botonOlvide);
        botonOlvide.setBounds(1040, 600, 240, 60);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1382, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int validarNumero(String str){
       
        if (str.matches("[0-9]+"))
            return 1;
        else
            return 0;
    }
    
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed

        String user, cont;
        user = usuario.getText();
        cont = pass.getText();

        Administrador admin;
        admin = controladorAdministrador.loginAdministrador(user);

        Gerente gen;
        gen = controladorGerente.loginGerente(user);

        Operador ope;
        ope = controladorOperador.loginOperador(user);
        
        
        
        if((!user.equals("")) && (!cont.equals(""))){
            
            if(admin.getUsuario().equals(user) ){

                if(admin.getContrasena().equals(cont)){
                    
                    GUI_Administrador interfazAdmin = new GUI_Administrador();
                    interfazAdmin.setVisible(true);
                    this.dispose();
                }
                else {

                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(gen.getCedula_ge().equals(user)){

                if(gen.getContrasena().equals(cont)){
                  
                    GUI_Gerente interfazGerente = new GUI_Gerente();
                    interfazGerente.setId(gen.getCedula_ge());
                    interfazGerente.setVisible(true);
                    this.dispose();
                }
                else {

                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(ope.getCedula_op().equals(user)){

                if(ope.getContrasena().equals(cont)){
                    
                    GUI_Operador interfazOperador = new GUI_Operador();
                    interfazOperador.setVisible(true);
                    interfazOperador.setId(ope.getCedula_op());
                    this.dispose();
                }
                else {

                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                
                JOptionPane.showMessageDialog(null, "El usuario no existe.\nVerifique sus datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "No ingresaste algún campo.\nVerifique sus datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxtPass;
    private javax.swing.JLabel TxtUsuario;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JLabel botonOlvide;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}